<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\Artisan;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // Shield's permissions/policies are generated by a CLI command, not
        // migrations, so `migrate:fresh` wipes the `permissions` table. It
        // must be regenerated before RoleSeeder can attach permissions to roles.
        Artisan::call('shield:generate', ['--all' => true, '--panel' => 'admin']);

        $this->call([
            RoleSeeder::class,
            LegacyFlymSeeder::class,
            SampleMembersSeeder::class,
            OfficialAdminUsersSeeder::class,
        ]);
    }
}
